### PR TITLE
Cannot run runtests.bat outside tests folder #107

### LINKED ISSUE #107: [Windows] Cannot run runtests.bat outside tests folder
User cannot run `tests/runtests.bat` if current directory is not `tests`.

/cc @damithc

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Allow user to run test script by invoking the script without having to switch current directory to `test`.

Fix #107

### CODE REVIEW

**Comment by rongjiecomputer** [comment]
> Missing commit message body. You would need to explain about the commit (what it is trying to fix, why are we fixing it, and how are we fixing it). Please refer to the "Commit message" under the Formats and Conventions documentation for more details. Do take note that you might have to do a bit more explaination for the "why" portion, because the Developer Guide already mentioned about running the script inside the test folder, so the justification for having this fix needs to be strong, in order for us to merge the PR.

Done. Am I supposed to write an essay for small commit to address reviewer's comments in a PR? That is way too verbose in my opinion.

> Commit subject line can be improved: There should be a mention of the test script filename, and it needs an imperative word at the start (suggestion: runtests.bat: Modify ...). The "[Windows]" word can be dropped.

Done.

> PR title should match the issue's title, with the issue number attached to the back: Cannot run runtests.bat outside tests folder #107

Done.

> Also, optionally, it would be great if you can supply an equivalent fix for Linux if possible (otherwise, do create a separate issue for Linux so that someone else can have a go at fixing the bash script).

I think can do the bash script one later. Let see how this PR goes first.

**Comment by pyokagan** [comment]
@rongjiecomputer 

> Am I supposed to write an essay for small commit to address reviewer's comments in a PR? That is way too verbose in my opinion.

For this project, we strive to remove as much noise as possible from the commit history caused by "correcting" earlier commits.

In other words, you can squash the two commits together.

**Comment by pyokagan** [comment]
The corresponding change for `runtests.sh` was already done in 3a8c7e8c5f0b8490afd104bb715507b436aa098b , so it should be fine.

**Comment by rongjiecomputer** [comment]
> In other words, you can squash the two commits together.

Done.

**Comment by rongjiecomputer** [comment]
@eugenepeh Thank you for your suggestion. Done.

**Comment by rongjiecomputer** [comment]
For some reason, the green "Submit new iteration" in https://canihasreview.pyokagan.com/se-edu/addressbook-level1/pull/108 gives me the following error.

```
403 Forbidden
Must have push access to view collaborator permission.
```

**Comment by pyokagan** [comment]
@rongjiecomputer Whoops, sorry, that was a regression from the update yesterday. You can try again now.

**Comment by rongjiecomputer** [comment]
@pyokagan All good now!

**Comment by rongjiecomputer** [comment]
Do I have to open 1 PR for addressbook2-4 again or there is a simpler way to get the change applied to the remaining 3 repos?

**Comment by eugenepeh** [comment]
@rongjiecomputer only AB2 needs similar modification, so I think you will have to open a similar PR for it. AB3 & 4 uses junit so it doesn't applies to them.

**Pull request merged**
