### PR TITLE
Fix file access errors in runtests.bat when case sensitive attribute is enabled on directories #111

### LINKED ISSUE #111: runtests.bat: File access errors when case sensitive attribute is enabled on directories
## Subject of the Issue
`runtests.bat` reports file access errors when the case sensitive attribute of `\src` or `\test` directories is enabled.

There are two related sub-problems discovered:
1. Typographical error in `runtests.bat:10` resulting in `javac` reporting a "file not found" error.
`javac  ..\src\seedu\addressbook\Addressbook.java -d ..\bin` should have been:
`javac ..\src\seedu\addressbook\AddressBook.java -d ..\bin`
2. `fc` file compare utility tool shipped with Windows (used in `runtests.bat:35` - `FC actual.txt expected.txt`) is unable to access files residing in directories with case sensitive attribute enabled

This unintentional bug was likely introduced with the release of [Windows 10 Redstone 4 Insider Build 17093](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17093), as the case sensitive attribute for directories was first introduced in this particular Windows 10 Insider Build (eventually released in Windows 10 Redstone 4 officially as well).

## Tested on Environment(s)
* Fully updated Windows 10 Version 1803 (April 2018 Update) a.k.a. Windows 10 Redstone 4
* Fully updated Windows 10 Version 1809 (October 2018 Update) a.k.a. Windows 10 Redstone 5
* [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) installed and enabled (required to reproduce this bug)
* Oracle JDK 9.0.4

### Steps to Reproduce
1. Ensure that WSL optional feature is installed and enabled by running the following command in PowerShell as Administrator:
```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
2. Restart the computer when prompted
3. Ensure that case sensitive attribute is enabled in `\src` directory:
```batch
C:\[REDACTED]\addressbook-level1>fsutil file setCaseSensitiveInfo .\src enable
Case sensitive attribute on directory C:\[REDACTED]\addressbook-level1\src is enabled.
```
4. Execute `runtests.bat`

### Expected Behaviour
No errors when running `runtests.bat`.

#### In `\test` directory:
```
C:\[REDACTED]\addressbook-level1\test>runtests.bat
        1 file(s) copied.

C:\[REDACTED]\addressbook-level1\test>echo %ERRORLEVEL%
0
```

#### Outside `\test` directory:
```
C:\[REDACTED]\addressbook-level1>test\runtests.bat
        1 file(s) copied.

C:\[REDACTED]\addressbook-level1>echo %ERRORLEVEL%
0
```

### Actual Behaviour
When running `runtests.bat`, `javac` reports a "file not found" error.

#### In `\test` directory:
```
C:\[REDACTED]\addressbook-level1\test>runtests.bat
javac: file not found: ..\src\seedu\addressbook\Addressbook.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********

C:\[REDACTED]\addressbook-level1\test>echo %ERRORLEVEL%
1
```

#### Outside `\test` directory:
```
C:\[REDACTED]\addressbook-level1>test\runtests.bat
javac: file not found: ..\src\seedu\addressbook\Addressbook.java
Usage: javac <options> <source files>
use --help for a list of possible options
********** BUILD FAILURE **********

C:\[REDACTED]\addressbook-level1>echo %ERRORLEVEL%
1
```

### Suggested Fix:
Simply replace `javac  ..\src\seedu\addressbook\Addressbook.java -d ..\bin` found at `runtests.bat:10` with `javac ..\src\seedu\addressbook\AddressBook.java -d ..\bin`.

### Steps to Reproduce
1. Ensure that WSL optional feature is installed and enabled by running the following command in PowerShell as Administrator:
```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
2. Restart the computer when prompted
3. Ensure that case sensitive attribute is enabled in `\test` directory:
```batch
C:\[REDACTED]\addressbook-level1>fsutil file setCaseSensitiveInfo .\test enable
Case sensitive attribute on directory C:\[REDACTED]\addressbook-level1\test is enabled.
```
4. Fix the typographical error in `runtests.bat:10` by replacing the affected line with: 
`javac ..\src\seedu\addressbook\AddressBook.java -d ..\bin`
5. Execute `runtests.bat`

### Expected Behaviour
No errors when running `runtests.bat`.

#### In `\test` directory:
```
C:\[REDACTED]\addressbook-level1\test>runtests.bat
        1 file(s) copied.

C:\[REDACTED]\addressbook-level1\test>echo %ERRORLEVEL%
0
```

#### Outside `\test` directory:
```
C:\[REDACTED]\addressbook-level1>test\runtests.bat
        1 file(s) copied.

C:\[REDACTED]\addressbook-level1>echo %ERRORLEVEL%
0
```

### Actual Behaviour
When running `runtests.bat`, `fc` reports a "no such file or folder" error.

#### In `\test` directory:
```
C:\[REDACTED]\addressbook-level1\test>runtests.bat
        1 file(s) copied.
FC: cannot open ACTUAL.TXT - No such file or folder

C:\[REDACTED]\addressbook-level1>echo %ERRORLEVEL%
2
```

#### Outside `\test` directory:
```
C:\[REDACTED]\addressbook-level1>test\runtests.bat
        1 file(s) copied.
FC: cannot open ACTUAL.TXT - No such file or folder

C:\[REDACTED]\addressbook-level1>echo %ERRORLEVEL%
2
```

### Suggested Fix:
Due to the way how the `fc` file compare Windows utility tool parses and transforms filepaths internally, one possible fix for this problem is to disable the case sensitivity attribute of `\test` directory, unless Microsoft fixes the way how the `fc` tool parses and interprets filepaths.

### PR DESCRIPTION
**Pull request by Creastery**
Fixes #111

### CODE REVIEW

**Comment by pyokagan** [comment]
Alternatively, if it turns out that Microsoft isn't really interested in updating stuff kept around for batch scripts compatibility, it might be time to rewrite `runtests.bat` into `runtests.ps1` :-)

**Comment by Creastery** [comment]
Hi @pyokagan, thanks for taking time to review!

> So, I was extremely confused reading this right after reading [1/2]. We are
> already calling `FC actual.txt expected.txt` with the correct exact filenames
> `actual.txt` and `expected.txt`, so why would it still be failing?
> 
> Anyway, I only got my answer by reading the issue description of #111, particularly the fact that the actual output from `FC` is:
> 
> ```
> C:\[REDACTED]\addressbook-level1\test>runtests.bat
>         1 file(s) copied.
> FC: cannot open ACTUAL.TXT - No such file or folder
> ```
> which makes it clear that `FC` is looking for `ACTUAL.TXT` for some reason.
> This should be written in the commit message.

Admittedly, the commit message could have been better phrased to include this detail. 
Any suggestions on how to refine it? :)

> Putting that aside, reading a bit further on #111, it seems that this is
> actually a bug in `FC`? If so, it's probably better to report it to Microsoft
> so that they can fix it.

Yes, this is a bug in `fc`. I guess it'll be fixed by Microsoft eventually, but bugs fixes related to WSL interoperability with Windows are generally slow in nature :/

> For this patch, I don't really see a point in applying it since it doesn't
> actually make case sensitive directories work with the codebase. I don't really
> think the troubleshooting entry is needed either -- the troubleshooting section is geared towards
> beginners. I suspect developers using WSL or playing with the case sensitivity
> attribute aren't them :-)

Actually, there are many developers (beginners included) who adopt the use of WSL for convenient access to UNIX utilities on Windows 10. Yet, most developers who use WSL are largely unfamiliar with how it works. 

I do agree that developers who toy around with case sensitivity attributes are probably not beginners and should know what they are doing. However, I think beginners are likely to trigger this bug accidentally and not realising it at all, and are unlikely to be able to resolve this particular bug on their own.

Directories created using WSL have the case sensitivity attribute enabled by default. If developers perform `git clone` on the repository under WSL, the case sensitive attribute of the all directories (including `\test`) created will be set to `enabled` automatically. Eventually, when these developers tests the program in Windows, `fc` will be unable to access the `actual.txt` and `expected.txt` files and will return the strange `No such file or folder` error. 

So far, I've yet to come across any search results online for similar bugs that are relevant in helping beginners to debug, identify and resolve this bug, which is why I believe it is still rather necessary to outright handle the `no such file or folder` error and include additional instructions under the troubleshooting section pertaining to this regression bug in Windows 10. 

> Alternatively, if it turns out that Microsoft isn't really interested in updating stuff kept around for batch scripts compatibility, it might be time to rewrite `runtests.bat` into `runtests.ps1` :-)

Windows PowerShell is indeed a convenient replacement for batch scripting, given that it is pre-installed in Windows 7 and later. However, do note that the `ExecutionPolicy` defaults to `Restricted`, which allows PowerShell to be used interactively only (no scripts can be executed). 

Personally, I don't think it would be a good idea to switch to a PowerShell script for testing because `ExecutionPolicy` needs to be set to `Unrestricted` to allow execution of the script. Doing so, firstly, requires administrator permissions, and secondly, weakens the host machine security :(

Let me know what you think!

**Comment by pyokagan** [comment]
> to implement another solution that supports case-sensitive directories such as rewriting `runtests.bat` in powershell.

Or a less intrusive solution (if we don't want to go full powershell) might be to package a `FileCompare.jar` and replace `FC` with `java -jar FileCompare.jar` :-)

**Comment by Creastery** [comment]
@pyokagan 
> I'm slightly negative on [2/2], though, because it kind of mixes up the goal of this PR. We need to be clear on: Do we want to support case-sensitive directories on Windows?
> 
> If yes, then [2/2] will run counter to that goal. A better solution would be either to (nicely :-)) ask Microsoft to fix `FC`, in which case [2/2] is not needed, or to implement another solution that supports case-sensitive directories such as rewriting `runtests.bat` in powershell.
> 
> If no, then [1/2] is not really needed (but can still be accepted for correctness sake, the commit message will need to be changed to mention that.) I'd also prefer a more explicit solution that checks to see if the `test` directory is case sensitive, and if so, bail out with an error. I don't really like checking the return code of `FC` because `FC` might also return 2 because the files are _actually_ missing. (e.g. the `expected.txt` file was accidentally deleted)

Checking if the `\test` directory is case sensitive is problematic because:
1. it only works on certain versions of Windows 10
2. there's no backward compatibility
3. requires parsing of the output (exit status are the same when the case sensitive attribute is enabled/disabled)

Perhaps consider this alternative fix instead -
Since `fc` does not work properly only when the case sensitive attribute of the `\test` directory is enabled, the developer must have WSL installed. So, `runtests.bat` can be amended to:
* Check if `actual.txt` and `expected.txt` exists prior to running the `fc` command
* If `fc` returns 2, attempt to run `diff` under WSL by running `wsl diff actual.txt expected.txt`
* If this fallback solution does not work, I guess it's probably better to prompt the developer to clone the repository again 🤔

**Comment by pyokagan** [comment]
@Creastery 

Would this work? I'd like to have consistent behavior between the case-sensitive-directory case and not if possible.

```diff
diff --git a/test/runtests.bat b/test/runtests.bat
index 7a75641..563e075 100644
--- a/test/runtests.bat
+++ b/test/runtests.bat
@@ -32,7 +32,7 @@ REM run the program, feed commands from input.txt file and redirect the output t
 java -classpath ..\bin seedu.addressbook.AddressBook < input.txt >> actual.txt

 REM compare the output to the expected output
-FC actual.txt expected.txt
+powershell "Compare-Object (Get-Content expected.txt) (Get-Content actual.txt)"

 REM return to previous directory
 popd

```

**Comment by Creastery** [comment]
Hey @pyokagan, 

> ```diff
> diff --git a/test/runtests.bat b/test/runtests.bat
> index 7a75641..563e075 100644
> --- a/test/runtests.bat
> +++ b/test/runtests.bat
> @@ -32,7 +32,7 @@ REM run the program, feed commands from input.txt file and redirect the output t
>  java -classpath ..\bin seedu.addressbook.AddressBook < input.txt >> actual.txt
> 
>  REM compare the output to the expected output
> -FC actual.txt expected.txt
> +powershell "Compare-Object (Get-Content expected.txt) (Get-Content actual.txt)"
> 
>  REM return to previous directory
>  popd
> ```

Unlike `fc`, `Compare-Object` cmdlet chooses to truncate output instead of wrapping to new lines.
I suggest piping the output to `Format-Table` cmdlet as such:
```powershell
powershell "Compare-Object (Get-Content expected.txt) (Get-Content actual.txt) | Format-Table -Wrap -AutoSize"
```

By the way, I discovered that renaming `actual.txt` and `expected.txt` to `ACTUAL.TXT` and `EXPECTED.TXT` respectively somehow enabled `fc` to detect and read the file contents successfully (tested on both Redstone 4 and 5 builds).

```
C:\[REDACTED]\addressbook-level1\test>fsutil file queryCaseSensitiveInfo .
Case sensitive attribute on directory C:\[REDACTED]\addressbook-level1\test is enabled.

C:\[REDACTED]\addressbook-level1\test>runtests.bat
        1 file(s) copied.
Comparing files ACTUAL.TXT and EXPECTED.TXT
FC: no differences encountered

C:\[REDACTED]\addressbook-level1\test>cd ..

C:\[REDACTED]\addressbook-level1>test\runtests.bat
        1 file(s) copied.
Comparing files ACTUAL.TXT and EXPECTED.TXT
FC: no differences encountered
```

Would you like to consider this as a potential fix instead?

**Comment by pyokagan** [comment]
@Creastery 
> By the way, I discovered that renaming `actual.txt` and `expected.txt` to `ACTUAL.TXT` and `EXPECTED.TXT` respectively somehow enabled `fc` to detect and read the file contents successfully (tested on both Redstone 4 and 5 builds).
> 
> ```
> C:\[REDACTED]\addressbook-level1\test>fsutil file queryCaseSensitiveInfo .
> Case sensitive attribute on directory C:\[REDACTED]\addressbook-level1\test is enabled.
> 
> C:\[REDACTED]\addressbook-level1\test>runtests.bat
>         1 file(s) copied.
> Comparing files ACTUAL.TXT and EXPECTED.TXT
> FC: no differences encountered
> 
> C:\[REDACTED]\addressbook-level1\test>cd ..
> 
> C:\[REDACTED]\addressbook-level1>test\runtests.bat
>         1 file(s) copied.
> Comparing files ACTUAL.TXT and EXPECTED.TXT
> FC: no differences encountered
> ```
> 
> Would you like to consider this as a potential fix instead?

Yes, that's a great idea :+1: Do remember to update `runtests.sh` and the gitignore file.

**Comment by Creastery** [comment]
@pyokagan,

> I don't have a Windows machine to test this on at present, but I ran
> `runtests.sh` and there aren't any regressions. I guess you have tested
> this on Windows :-P

Indeed, I tested it on the affected Windows systems, as well as in Linux, before pushing the commit!

Thanks for the suggestion on how to make the commit message more succinct! 
I've updated the commit message accordingly :)

**Comment by Creastery** [comment]
> Minor typo in commit message (`attribute` repeated):
> 
> ```
> Although it is unlikely that developers enable the case attribute
> attribute on the `test` directory intentionally, developers may
> ```

Whoops, so sorry about that!

**Comment by damithc** [comment]
@Creastery noted you are doing CS2113 this semester. Great job on getting a PR merged to se-edu so early in the semester. I encourage you to contribute more to [se-edu or other NUS-OSS](https://nus-oss.github.io/) projects in future if you are inclined in that direction.

**Comment by Creastery** [comment]
Thanks for the encouragement, Prof! It was a good learning experience for me :)

**Pull request merged**
